#  Assignment 5

This assignment covers material on matrices, norms, condition numbers and eigensystems. The assignment is due by 5pm on Friday the 17th of April.

The breakdown of the marks is as follows:

Question 0 - [1 mark]  
Question 1 - [7 marks]  
Questino 2 - [6 marks]  
Question 3 - [7 marks]  
Question 4 - [9 marks]  

# Question 0

You should have saved this notebook to your ACM20030-Assignments folder. Now:
- commit the notebook to your local repository
- push the changes to the GitHub

In [53]:
import numpy as np
from numpy import linalg as la
np.set_printoptions(linewidth=200)  # This stops line wrapping of larger matrices

# Question 1 - practice manipulating arrays

This questions asks you write a few functions for manipulating arrays of data

## Q1 a

Write a function that checks if a given $n\times n$ matrix is symmetric. Use only loops and `.shape` function from numpy (do not use any other special numpy functions).

In [54]:
 def matrix_symmetry(matrix):
        symmetric = True
        for x in range(len(matrix)):
            for y in range(len(matrix[x])):
                if matrix[x][y] != matrix[y][x]:
                    symmetric = False
                    break # inner for loop
            if not symmetric:
                break # outer for loop
        print("Is the matrix symmetric?",symmetric)

Test your function on the two matrices below

In [55]:
A = np.random.rand(5,5)
SymMatrix = (A + A.T)/2

In [56]:
matrix_symmetry(A)

Is the matrix symmetric? False


In [57]:
matrix_symmetry(SymMatrix)

Is the matrix symmetric? True


## Q1 b

Write a function to transpose a general $n\times n$ matrix. Do this by writing loops and not using any special functions like `np.transpose()`, `A.T`, or any functions from any other library.

In [58]:
def transpose(matrix):
    end_result = np.empty([len(matrix),len(matrix)])
            
    for i in range(len(matrix)):
        for j in range(len(matrix[0])):
            end_result[j][i] = matrix[i][j]
            
    return end_result

Check your code by transposing the below random matrix and checking that $A^T \neq A$ and $(A^T)^T - A = 0$

In [59]:
A = np.random.rand(6,6)

print("The matrix A is:\n", A)
print("The transpose of A is:\n", transpose(A))

print("The transpose of the transpose of A minus A is:\n", transpose(transpose(A)) - A)

The matrix A is:
 [[0.02495381 0.32952748 0.90877555 0.99468917 0.99087953 0.58156202]
 [0.59636027 0.3118155  0.15203177 0.3866347  0.24919321 0.89592072]
 [0.55999755 0.12656735 0.24468321 0.85234292 0.81778497 0.31307489]
 [0.11192294 0.60181794 0.57506289 0.59539868 0.09696927 0.74949583]
 [0.69750225 0.40110545 0.12357076 0.89391167 0.09166225 0.9564665 ]
 [0.01236514 0.30589152 0.0198638  0.76473013 0.32601991 0.69588412]]
The transpose of A is:
 [[0.02495381 0.59636027 0.55999755 0.11192294 0.69750225 0.01236514]
 [0.32952748 0.3118155  0.12656735 0.60181794 0.40110545 0.30589152]
 [0.90877555 0.15203177 0.24468321 0.57506289 0.12357076 0.0198638 ]
 [0.99468917 0.3866347  0.85234292 0.59539868 0.89391167 0.76473013]
 [0.99087953 0.24919321 0.81778497 0.09696927 0.09166225 0.32601991]
 [0.58156202 0.89592072 0.31307489 0.74949583 0.9564665  0.69588412]]
The transpose of the transpose of A minus A is:
 [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.

## Q1c

Write a function that finds the maximum entry in a matrix (where the matrix does not need to be square). Do this by writing loops and not using any special functions like `np.max` or any functions from any other library.

In [60]:
def max_matrix(my_matrix):

    max = 0
    n = 0
    
    while n < len(my_matrix):
        for i in my_matrix:
            for j in my_matrix[n]:
                if j > max:
                    max = j
            n += 1

            
    return max

Check your result by comparing to `np.max(A)` for the below random matrix

In [61]:
A = np.random.rand(4,5)

max_matrix(A)

0.9849844458527883

In [62]:
np.max(A)

0.9849844458527883

# Question 2:  matrix norms

In the lectures we focused on the $L^2$-norm. We also briefly mentioned the $L^1$ and $L^\infty$ norm. Let's look at calculating those as well for a general $m\times n$ matrix.

# Q2a

The $L^1$ norm is given by

$$ \lVert A \rVert_1 = \max_j \sum^m_{i=1} |a_{ij}| $$

i.e., it is the max of the sums of the absolute values of each column. Write a function that computes the $L^1$-norm using only loops. The function should use no special numpy functions except `np.abs()`.

In [63]:
# L1_norm = abs(x1)+abs(x2)+...+abs(xn)
# column1 = A[:,0]
# column2 = A[:,1]
# column3 = A[:,2]

def L1_norm(matrix):
    n = 0
    m =0
    max = 0
    find_max = [] # the list we want to find the max of
    
    while n < len(matrix[0]):
        sum = 0
        for i in matrix[:,n]:
            sum += np.abs(i)
        find_max.append(sum)
        n += 1
        
    
    while m < len(find_max):
        for i in find_max:
            if i > max:
                max = i
        m += 1
    print(max)

Check your result against NumPy's `la.norm(A,1)` function for the following random matrix

In [64]:
A = np.random.rand(3,4)

L1_norm(A)

2.0028692936404258


In [65]:
la.norm(A,1)

2.0028692936404258

## Q2b

The $L^\infty$ norm is given by 

$$\lVert A \rVert_\infty = \max_i \sum_{j=1}^n |a_{ij}|$$

i.e., it is the max of the sums of the absolute values of each row. Write a function that computes the $L^\infty$-norm using only loops and no special numpy functions.

In [66]:
# row1 = A[0,:]
# row2 = A[1,:] ...etc.

def L_inf_norm(matrix):
    n = 0
    find_max = [] # we want to find the max of this list
    m = 0
    max = 0
    
    while n < len(matrix):
        sum = 0
        for i in matrix[n,:]:
            sum += abs(i)
        find_max.append(sum)
        n += 1
        
    while m < len(find_max):
        for i in find_max:
            if i > max:
                max = i
        m += 1
    print(max)

Check your result against NumPy's `la.norm(A,np.inf)` function for the following random matrix

In [67]:
A = np.random.rand(3,4)

L_inf_norm(A)

2.163369825041647


In [68]:
la.norm(A, np.inf)

2.163369825041647

# Question 3: ill-conditions systems of equations

In this question you can use any of NumPy's functions.

## Q3a

Which of the following three matrices, $A1, A2, A3$, are ill-conditioned. State the reason for your conclusion.

In [69]:
A1 = np.array([[0.988746460106, 0.351486109477, 0.024911477532, 0.384039749683],
       [0.282104657306, 0.239884151775, 0.36170151991 , 0.903082266861],
       [0.59333290915 , 0.637178863968, 0.241229214635, 0.685595037901],
       [0.013591747828, 0.917926970364, 0.458689093885, 0.157821121254]])

A2 = np.array([[ 2.852416473483e-01,  3.803483118694e-01,  2.697704226632e-01,  6.810611849029e-01],
       [ 6.622827828376e-01,  6.447943415836e-01,  4.387842058829e-01,  1.530575702376e+00],
       [ 3.672130860703e-01,  8.309522079704e-01,  9.975487474007e-01,  5.678296337101e-01],
       [ 4.036490000599e-01,  6.865978225967e-06,  8.788095913773e-01, -7.150472427928e-02]])

A3 = np.array([[0.131923621844, 0.245316154195, 0.732362341613, 0.957047891764],
       [0.91290446184 , 0.512312007959, 0.391938831444, 0.092509684772],
       [0.648708523652, 0.608576675797, 0.576773587276, 0.065385122929],
       [0.502955480393, 0.084082960221, 0.659487390444, 0.662958739412]])

In [70]:
# The formula for the condition number based on the norm definition = la.norm(matrix,2)*la.norm(la.inv(matrix),2))

A1_cond_no = la.norm(A1,2)*la.norm(la.inv(A1),2)
A2_cond_no = la.norm(A2,2)*la.norm(la.inv(A2),2)
A3_cond_no = la.norm(A3,2)*la.norm(la.inv(A3),2)

print("Condition number for the matrix A1:", A1_cond_no)
print("Condition number for the matrix A2:", A2_cond_no)
print("Condition number for the matrix A3:", A3_cond_no)

Condition number for the matrix A1: 21.552466488381857
Condition number for the matrix A2: 13334921820.764688
Condition number for the matrix A3: 15.122449699410627


In [71]:
# If a condition number is not much larger than 1, then the matrix is well-conditioned, meaning its inverse can be
# computed with great accuracy.

# If a condition number is very large, the matrix is said to be ill-conditioned.

# As can be seen above, System 2 has a very large condition number, showing that this system is ill-conditioned.

# Q3b

With $b = [1,2,3,4]$ and $\delta b = [0.1,0,0,0]$ for $A2$ and $A3$ calculate the percentage change in $x$ due to a small change in $b$, i.e., calculate 

$$100\times\frac{\lVert \delta x_i\rVert_2}{\lVert x_i \rVert_2}\quad\text{and}\quad 100\times\frac{\lVert \delta b\rVert_2}{\lVert b \rVert_2}$$

where $(x_i+\delta x_i)  = A_i^{-1}(b+\delta b)$ and $i\in\{2,3\}$.

In [72]:
def GaussianElimination(A, b):
    n = A.shape[1]
    
    # Append the vector b as a column to the matrix A
    A1 = np.c_[A,b]
    
    i = 0
    while i < n - 1:
        j = i+1
        while j < n:
            A1[j, i+1:] = A1[j, i+1:] - A1[i, i+1:]*A1[j,i]/A1[i,i]
            j += 1
        i += 1
        
    x = np.zeros(n)
    
    i = n-1
    while i >= 0:
        j = i
        x[i] = A1[i,n]
        while j < n-1:
            x[i] -= A1[i,j+1]*x[j+1]
            j += 1
        x[i] = x[i]/A1[i,i]
        i -= 1
    
    return x

def L2Norm(v):
    return la.norm(v,2)

In [73]:
b = np.array([1,2,3,4])
bp = np.array([1.1,2,3,4])

x2 = GaussianElimination(A2,b)
x2p = GaussianElimination(A2,bp)

x3 = GaussianElimination(A3,b)
x3p = GaussianElimination(A3,bp)

In [74]:
print("Change in b = %.4f%%" % (100*L2Norm(bp-b)/L2Norm(b)))
print("Change in x2 = %.2f%%" % (100*L2Norm(x2p-x2)/L2Norm(x2)))

print("Change in b = %.4f%%" % (100*L2Norm(bp-b)/L2Norm(b)))
print("Change in x3 = %.2f%%" % (100*L2Norm(x3p-x3)/L2Norm(x3)))

Change in b = 1.8257%
Change in x2 = 512.62%
Change in b = 1.8257%
Change in x3 = 2.17%


Which system of equations is more sensitive to small changes in $b$? How could you have guessed this from the answer to the Q3a?

In [75]:
# Answer here
# System 2 is more sensitive to small changes in b, as can be seen above a small change in b results in a 512.62%
# change in x2.

# Question 4: eigensystems

In this question we look at finding eigenvalues and eigenvectors

## Q4a

You may use any of NumPy's functions for this sub-question.

Find the eigenvalues and eigenvectors for the below matrix. Print out the eigenvalues sorted by descending value and explicitly show that eigenvalues/eigenvector pairs satisfy $Ax = \lambda x$.

In [76]:
A = np.array([[1,4,5],[4,5,4],[6,7,9]])

In [77]:
eigenSystem = la.eig(A)
eigenValues = eigenSystem[0]
eigenVectors = eigenSystem[1]

i = eigenValues.argsort()[::-1]
eigenValues = eigenValues[i]
eigenVectors = eigenVectors[:,i]

print(eigenValues)

[15.78569318  1.26595327 -2.05164645]


In [78]:
# Showing Ax = lambdax

x = np.random.rand(3)

print(np.dot(A,eigenSystem[1][:,0]))
print(eigenSystem[0][0]*eigenSystem[1][:,0])

[ -6.1962015   -7.01266016 -12.71289871]
[ -6.1962015   -7.01266016 -12.71289871]


# Q4b

Without using NumPy's `la.eig()` (or similar functions), find the 4 eigenvalues and eigenvectors of the following matrix. Hint: Use the power method for the max eigenvalue (given below in `MaxEigenvalue`), the power method applied to the inverse for the smallest eigenvalue, and apply Hotelling's deflation twice to find the second and third eigenvalues/eigenvectors.

In [79]:
A = np.array([[1.935052353404, 0.887037260957, 1.534235483277, 1.370691224125],
       [0.887037260957, 0.81275989158 , 0.610238622918, 0.999150521052],
       [1.534235483277, 0.610238622918, 1.562260333538, 1.007843062517],
       [1.370691224125, 0.999150521052, 1.007843062517, 1.813258814483]])

In [80]:
# Max eigenvalue

def MaxEigenvalue(A, err):
    (m,n) = A.shape
    if(m != n):
        print("Matrix must be square")
        return
    x = np.random.rand(m)
    
    lam = 0.1
    lamprev = 1
    while np.abs(1-lam/lamprev) > err:
        p = np.dot(A,x)
        lamprev = lam
        lam = np.max(p)
        x = p/lam
        
    x = x/la.norm(x)
    return (lam,x)

MaxEigen = MaxEigenvalue(A, 1e-14)

In [81]:
# Min eigenvalue

MinEigen = 1/MaxEigenvalue(la.inv(A), 1e-14)[0]

In [82]:
# Hotelling's equation for the second largest eigenvalue

l1 = MaxEigen[0]
e1 = MaxEigen[1]

B = A - l1*np.outer(e1,e1)

lsecond = MaxEigenvalue(B, 1e-14)

In [83]:
# Hotelling's equation a second time for the third largest eigenvalue

l2 = lsecond[0]
e2 = lsecond[1]

C = B - l2*np.outer(e2,e2)

lthird = MaxEigenvalue(C, 1e-14)

In [84]:
print(MaxEigen)
print(lsecond)
print(lthird)
print(MinEigen)

(4.9148044234997705, array([0.59947641, 0.33318806, 0.49528112, 0.53320761]))
(0.85058153186663, array([-0.30724064,  0.3894447 , -0.58292464,  0.64353313]))
(0.21512836395693558, array([ 0.3811686 ,  0.67389895, -0.34000478, -0.53382343]))
0.14281707368166774


Check your answers against Numpy's results from `la.eig(A)`

In [85]:
la.eig(A)

(array([4.91480442, 0.85058153, 0.14281707, 0.21512836]),
 array([[ 0.59947641,  0.30724064, -0.63319959, -0.3811686 ],
        [ 0.33318806, -0.3894447 ,  0.53214542, -0.67389895],
        [ 0.49528112,  0.58292464,  0.54707607,  0.34000478],
        [ 0.53320761, -0.64353313, -0.12879172,  0.53382343]]))